### ISSUE TITLE
Callback onPermissionGranted called, but permision is not granted

### ISSUE THREAD

**Issue by CJure** [nishkarsh/android-permissions#1] opened 2017-06-13 13:07 UTC
On create() I have this part of code:

```
 PermissionManager permissionManager = PermissionManager.getInstance(this);
         permissionManager.checkPermissions(singleton(Manifest.permission.USE_FINGERPRINT), new PermissionManager.PermissionRequestListener() {
             @Override
             public void onPermissionGranted() {
                 Toast.makeText(getBaseContext(), "Permissions Granted", Toast.LENGTH_SHORT).show();
                 fingerprintCheckBox.setEnabled(true);
 
             }
 
             @Override
             public void onPermissionDenied() {
                 Toast.makeText(getBaseContext(), "Permissions Denied", Toast.LENGTH_SHORT).show();
             }
         });
```

But when I check if the permission is granted:

` if (ActivityCompat.checkSelfPermission(this, Manifest.permission.USE_FINGERPRINT) != PackageManager.PERMISSION_GRANTED)`

it returns FALSE.

**Comment by nishkarsh** [comment] 2017-06-13 15:00
@CJure Where have you placed this check? Which callback do you get when you click on "Allow" for the permission when asked?

**Comment by CJure** [comment] 2017-06-14 19:11
@nishkarsh I have this check inside Activity that extends AppCompatActivity and is called and is called inside the method that gets called onCreate.
Callback is onPermissionGranted.

**Comment by nishkarsh** [comment] 2017-06-27 14:59
@CJure Can you please submit sample code to help me reproduce this?
Thanks!

**Comment by nishkarsh** [comment] 2017-10-29 17:11
Closing this as the issue is not reproducible and sample code hasn't been provided to produce the issue.

**Closed by nishkarsh** 2017-10-29 17:11 UTC
