### ISSUE TITLE
Incompatible with API 27

### ISSUE THREAD

**Issue by ghost** [nishkarsh/android-permissions#2] opened 2017-10-27 20:45 UTC
Breaks builds with API 27

https://github.com/nishkarsh/android-permissions/blob/971bc85d50db9145e12e83494efe33b4f7e66e11/src/main/AndroidManifest.xml#L11

**Comment by nishkarsh** [comment] 2017-11-03 18:59
Hey @AngelBob!
Thanks for reporting the issue! I tested the library after upgrading targetSdk and all other dependencies to 27, it works fine. Could you please post the logs that include the error as I couldn't reproduce it?

I would be pushing an update to the library soon with the upgraded targetSdkVersion and other dependencies.

**Comment by AngelBob** [comment] 2017-11-06 07:20
Sure,
Here's a log from a crash
`FATAL EXCEPTION: main
                                                                              Process: studio.dontblink.blinkspeedo, PID: 29129
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{studio.dontblink.blinkspeedo/com.intentfilter.androidpermissions.PermissionsActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                  at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                               Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
                                                                                  at android.app.Activity.onCreate(Activity.java:986)
                                                                                  at android.support.v4.app.SupportActivity.onCreate(SupportActivity.java:66)
                                                                                  at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:297)
                                                                                  at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
                                                                                  at com.intentfilter.androidpermissions.PermissionsActivity.onCreate(PermissionsActivity.java:29)
                                                                                  at android.app.Activity.performCreate(Activity.java:6975)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                                  at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                  at android.os.Looper.loop(Looper.java:164) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

This is running on a Google Pixel with Oreo build OPR3.170623.008

**Comment by nishkarsh** [comment] 2017-11-06 16:51
Thanks for reporting the issue. Your pull request has been merged and a new version of android-permissions would be released soon.

**Closed by nishkarsh** 2017-11-06 16:51 UTC
Labels: need more details
